### ISSUE TITLE
Manual renders poorly

### ISSUE THREAD

**Issue by NickBarnes** [rptb1/sl-forth#1]
The Manual file renders poorly in the github UI.  It would be much better called Manual.rst (and possibly with a small amount of markup).

**Comment by rptb1** [comment]
The manual is in the appropriate format for a Second Life notecard (which is what it was).  That's probably of historical interest only, though.

**Comment by rptb1** [comment]
Fixed in 55ded62221c2c80ba4cd9be9971dbe675e03c27a.
